### ISSUE TITLE
网页版正常python版报错

### ISSUE THREAD

**Issue by GodBlessNoBugs** [mos9527/ncm-afp#2]
用同一个音频文件网页版正常识别:
![image](https://github.com/mos9527/ncm-afp/assets/28342500/595c87b1-d7be-4629-bf80-3390ca495e2e)
Python版报错，换音频文件也不行：
![image](https://github.com/mos9527/ncm-afp/assets/28342500/d8f3b78a-bbe1-4aee-ac9b-599f7317bbf9)

**Comment by mos9527** [comment]
你打的是什么命令？
同时，也可以参考这个comment和这里的数据测试afp的可用性 https://github.com/mos9527/ncm-afp/issues/1#issuecomment-2106183007
